### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by tolgabirdal** [takmin/BinaryCvMat#1]
The following must be changed:

ReadMatBinary -> readMatBinary
WriteMatBinary -> writeMatBinary

**Comment by takmin** [comment]
Why is that change needed?

**Comment by tolgabirdal** [comment]
Well it's a syntax error.

**Comment by takmin** [comment]
Please tell me your environment and minimal steps to reproduce the syntax error.

**Comment by tolgabirdal** [comment]
In any environment, this would generate a syntax error because:

The function LoadMatBinary makes a call to ReadMatBinary, which doesn't exist. What exists is readMatBinary. So ReadMatBinary should be changed to readMatBinary to avoid the compilation error.
Same for the WriteMatBinary ..

**Comment by takmin** [comment]
Thank you. I fixed it.
